import type { OxelotMutation, SyncState } from './envelope'
import { serializeMutation, deserializeMutation } from './envelope'
import { nextRetryDelayMs, isDeadLetter } from './scheduler'
import { oxError } from '../../errors'

const QUEUE_KEY = 'oxelot.sync.queue'
const DEAD_KEY = 'oxelot.sync.dead'
const SYNC_LOCK = 'oxelot-sync'
export const SYNC_TAG = 'oxelot-sync'

export interface KvLike {
  get<T>(key: string): Promise<T | null>
  set<T>(key: string, value: T): Promise<void>
}

/** Structural lock manager; satisfied by `WebLock`. */
export interface SyncLock {
  tryWithLock<T>(name: string, fn: () => Promise<T>): Promise<{ acquired: boolean; result?: T }>
}

export interface SyncDelivery {
  deliver(m: OxelotMutation): Promise<void>
}

export interface SyncService {
  enqueue(m: OxelotMutation): Promise<void>
  /** Next due envelope without removing it (used for previews/diagnostics). */
  peek(): Promise<OxelotMutation | null>
  flush(): Promise<{ delivered: number; deadLetters: number }>
  status(): Promise<{ pending: number; deadLetters: number }>
  onStateChange(cb: (s: SyncState) => void): () => void
}

export interface PersistentSyncQueueOptions {
  /**
   * Persist the queue after every N processed envelopes during a drain. Bounds
   * crash-mid-drain re-delivery: at most `checkpoint` already-delivered
   * envelopes can still be in-flight after a crash (consumer idempotency by
   * stable envelope `id` covers the rest). Default 50.
   */
  checkpoint?: number
}

export class PersistentSyncQueue implements SyncService {
  private readonly listeners = new Set<(s: SyncState) => void>()
  private flushing = false
  private readonly checkpoint: number

  constructor(
    private readonly kv: KvLike,
    private readonly deliver: SyncDelivery,
    private readonly lock?: SyncLock,
    options: PersistentSyncQueueOptions = {},
  ) {
    this.checkpoint = options.checkpoint ?? 50
  }

  async enqueue(m: OxelotMutation): Promise<void> {
    const queue = (await this.kv.get<OxelotMutation[]>(QUEUE_KEY)) ?? []
    // Exactly-once by stable envelope id: re-sending the same mutation (id is
    // generated by core, stable across retries) must not double-queue it.
    if (queue.some((x) => x.id === m.id)) return
    queue.push(m)
    await this.kv.set(QUEUE_KEY, queue)
    this.emit({ kind: 'queued', pending: queue.length })
  }

  async peek(): Promise<OxelotMutation | null> {
    const queue = (await this.kv.get<OxelotMutation[]>(QUEUE_KEY)) ?? []
    const now = Date.now()
    return queue.find((m) => m.nextRetryAt == null || m.nextRetryAt <= now) ?? null
  }

  async flush(): Promise<{ delivered: number; deadLetters: number }> {
    if (this.flushing) return { delivered: 0, deadLetters: 0 }
    this.flushing = true
    try {
      if (this.lock) {
        const held = await this.lock.tryWithLock(SYNC_LOCK, () => this.drain())
        if (!held.acquired) return { delivered: 0, deadLetters: 0 }
        return held.result ?? { delivered: 0, deadLetters: 0 }
      }
      return await this.drain()
    } finally {
      this.flushing = false
    }
  }

  async status(): Promise<{ pending: number; deadLetters: number }> {
    const queue = (await this.kv.get<OxelotMutation[]>(QUEUE_KEY)) ?? []
    const dead = (await this.kv.get<OxelotMutation[]>(DEAD_KEY)) ?? []
    return { pending: queue.length, deadLetters: dead.length }
  }

  onStateChange(cb: (s: SyncState) => void): () => void {
    this.listeners.add(cb)
    return () => this.listeners.delete(cb)
  }

  /**
   * Drain the queue, delivering only envelopes that are due (no pending backoff
   * period). An envelope is removed only after a successful delivery (pop-on-
   * success); the current queue state is persisted every `checkpoint` processed
   * envelopes so a crash mid-drain cannot re-deliver more than `checkpoint`
   * already-sent envelopes. Transient failures increment `attempts`, stamp
   * `nextRetryAt`, and are kept for a later flush; permanent failures are
   * quarantined as dead letters.
   */
  private async drain(): Promise<{ delivered: number; deadLetters: number }> {
    const result = { delivered: 0, deadLetters: 0 }
    const queue = (await this.kv.get<OxelotMutation[]>(QUEUE_KEY)) ?? []
    const dead = (await this.kv.get<OxelotMutation[]>(DEAD_KEY)) ?? []
    if (queue.length === 0) {
      this.emit({ kind: 'idle' })
      return result
    }
    this.emit({ kind: 'syncing', pending: queue.length })

    const now = Date.now()
    const remaining: OxelotMutation[] = []
    let attempted = 0
    let i = 0
    for (const m of queue) {
      i++
      if (m.nextRetryAt != null && m.nextRetryAt > now) {
        remaining.push(m)
        continue
      }
      m.attempts += 1
      attempted++
      try {
        await this.deliver.deliver(m)
        result.delivered++ // success → m is not re-queued (atomic pop)
      } catch (err) {
        m.lastError = err instanceof Error ? err.message : String(err)
        if (isDeadLetter(m.attempts)) {
          dead.push(m)
          result.deadLetters++
        } else {
          m.nextRetryAt = now + nextRetryDelayMs(m.attempts)
          remaining.push(m)
        }
      }
      if (attempted % this.checkpoint === 0) {
        // Persist the kept (backoff/dead-letter-pending) prefix AND the
        // not-yet-attempted tail, so a crash mid-drain loses at most
        // `checkpoint` already-delivered envelopes.
        await this.kv.set(QUEUE_KEY, [...remaining, ...queue.slice(i)])
        await this.kv.set(DEAD_KEY, dead)
      }
    }
    const pending = remaining.length
    await this.kv.set(QUEUE_KEY, remaining)
    await this.kv.set(DEAD_KEY, dead)
    this.emit(
      pending > 0
        ? { kind: 'queued', pending }
        : result.deadLetters > 0
          ? { kind: 'dead_letter', pending: 0, deadLetters: dead.length }
          : { kind: 'idle' },
    )
    return result
  }

  private emit(state: SyncState): void {
    for (const cb of this.listeners) cb(state)
  }
}

export interface FetchSyncDeliveryOptions {
  serverUrl: string
  fetchImpl?: typeof fetch
}

export class FetchSyncDelivery implements SyncDelivery {
  private readonly fetchImpl: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>

  constructor(private readonly options: FetchSyncDeliveryOptions) {
    // `fetch` is a method on the global scope (Window/WorkerGlobalScope) and
    // throws "Illegal invocation" when called through a stored reference. Bind
    // it so flush works from both the page and the service worker.
    this.fetchImpl = (options.fetchImpl ?? fetch).bind(globalThis)
  }

  async deliver(m: OxelotMutation): Promise<void> {
    let res: Response
    try {
      res = await this.fetchImpl(this.options.serverUrl, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: serializeMutation(m),
      })
    } catch (err) {
      const cause = err instanceof Error ? err.message : String(err)
      throw oxError('ERR_SYNC_NETWORK', `network failure during sync flush (${cause})`, err)
    }
    if (res.ok) return
    if (res.status >= 500 || res.status === 408 || res.status === 429) {
      throw oxError('ERR_SYNC_NETWORK', `retryable status ${res.status}`)
    }
    throw oxError('ERR_SYNC_REJECTED', `permanent status ${res.status}`)
  }
}

export const retryDelay = nextRetryDelayMs
export { deserializeMutation, SYNC_LOCK }