import type { OxelotMutation, SyncState } from './envelope'
import { serializeMutation, deserializeMutation } from './envelope'
import { nextRetryDelayMs, isDeadLetter } from './scheduler'
import { oxError } from '../../errors'

const QUEUE_KEY = 'oxelot.sync.queue'
const CHUNK_PREFIX = 'oxelot.sync.queue.c.'
const DEAD_KEY = 'oxelot.sync.dead'
const SYNC_LOCK = 'oxelot-sync'
export const SYNC_TAG = 'oxelot-sync'

/** Manifest layout version. The legacy v1 layout stored one array under `QUEUE_KEY`. */
const MANIFEST_VERSION = 2
const DEFAULT_CHUNK_SIZE = 500

export interface KvLike {
  get<T>(key: string): Promise<T | null>
  set<T>(key: string, value: T): Promise<void>
}

/** Structural lock manager; satisfied by `WebLock`. */
export interface SyncLock {
  withLock<T>(name: string, fn: () => Promise<T>): Promise<T>
  tryWithLock<T>(name: string, fn: () => Promise<T>): Promise<{ acquired: boolean; result?: T }>
}

export interface SyncDelivery {
  deliver(m: OxelotMutation): Promise<void>
}

export interface SyncService {
  enqueue(m: OxelotMutation): Promise<void>
  /** Next due envelope without removing it (used for previews/diagnostics). */
  peek(): Promise<OxelotMutation | null>
  flush(): Promise<{ delivered: number; deadLetters: number }>
  status(): Promise<{ pending: number; deadLetters: number }>
  onStateChange(cb: (s: SyncState) => void): () => void
}

export interface PersistentSyncQueueOptions {
  /**
   * Persist the queue after every N processed envelopes during a drain. Bounds
   * crash-mid-drain re-delivery: at most `checkpoint` already-delivered
   * envelopes can still be in-flight after a crash (consumer idempotency by
   * stable envelope `id` covers the rest). Default 50.
   */
  checkpoint?: number
  /**
   * Max envelopes persisted per chunk key (`oxelot.sync.queue.c.<i>`, v2
   * layout). Small chunks keep enqueue and drain-checkpoint writes O(chunk)
   * instead of rewriting the whole queue; the manifest plus two-phase
   * compaction keep cross-realm readers consistent. Default 500.
   */
  chunkSize?: number
}

interface QueueManifest {
  v: typeof MANIFEST_VERSION
  /** Chunk-key offset of the live view (`chunkKey(base + i)` for i < chunkCount). */
  base: number
  /** Advisory fast-path count for status(); drains recompute truth from chunks. */
  count: number
  chunkSize: number
  chunkCount: number
}

function chunkKey(index: number): string {
  return `${CHUNK_PREFIX}${index}`
}

function isManifest(v: unknown): v is QueueManifest {
  return (
    typeof v === 'object' &&
    v !== null &&
    (v as { v?: unknown }).v === MANIFEST_VERSION &&
    typeof (v as { base?: unknown }).base === 'number' &&
    typeof (v as { chunkCount?: unknown }).chunkCount === 'number' &&
    typeof (v as { chunkSize?: unknown }).chunkSize === 'number'
  )
}

function splitChunks(items: OxelotMutation[], size: number): OxelotMutation[][] {
  const out: OxelotMutation[][] = []
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size))
  return out
}

function totalCount(chunks: OxelotMutation[][]): number {
  return chunks.reduce((n, c) => n + c.length, 0)
}

/**
 * Read the live queue in FIFO order regardless of the persisted layout
 * (v2 manifest + chunks, or the legacy v1 single-array key). Used by tests,
 * diagnostics, and consumers that want to inspect the shared queue directly;
 * the enqueue/drain paths load state through their own hot paths.
 */
export async function loadPersistedQueue(kv: KvLike): Promise<OxelotMutation[]> {
  const head = await kv.get<unknown>(QUEUE_KEY)
  if (head === null || typeof head !== 'object') return []
  if (isManifest(head)) {
    const out: OxelotMutation[] = []
    for (let i = 0; i < head.chunkCount; i++) {
      const chunk = await kv.get<OxelotMutation[]>(chunkKey(head.base + i))
      if (Array.isArray(chunk)) out.push(...chunk)
    }
    return out
  }
  return Array.isArray(head) ? (head as OxelotMutation[]) : []
}

export class PersistentSyncQueue implements SyncService {
  private readonly listeners = new Set<(s: SyncState) => void>()
  private flushing = false
  private readonly checkpoint: number
  private readonly chunkSize: number

  constructor(
    private readonly kv: KvLike,
    private readonly deliver: SyncDelivery,
    private readonly lock?: SyncLock,
    options: PersistentSyncQueueOptions = {},
  ) {
    this.checkpoint = options.checkpoint ?? 50
    this.chunkSize = Math.max(1, options.chunkSize ?? DEFAULT_CHUNK_SIZE)
  }

  async enqueue(m: OxelotMutation): Promise<void> {
    const { manifest, chunks } = await this.loadState()
    // Exactly-once by stable envelope id: re-sending the same mutation (id is
    // generated by core, stable across retries) must not double-queue it.
    // Scanned tail-first because duplicate re-enqueues usually happen close
    // together in time; early exit keeps the common case cheap.
    for (let i = chunks.length - 1; i >= 0; i--) {
      if (chunks[i]!.some((x) => x.id === m.id)) return
    }
    // Append into the tail chunk when it has room, else open a new one. Only
    // the touched chunk key is rewritten — O(chunk), not O(queue).
    const idx = chunks.length - 1
    if (idx >= 0 && chunks[idx]!.length < this.chunkSize) chunks[idx]!.push(m)
    else chunks.push([m])
    await this.kv.set(chunkKey(manifest.base + chunks.length - 1), chunks[chunks.length - 1]!)
    const pending = totalCount(chunks)
    // chunkCount must track chunks.length even though only one key was
    // touched: opening a new chunk makes the live view grow by one.
    await this.kv.set(QUEUE_KEY, { ...manifest, count: pending, chunkCount: chunks.length })
    this.emit({ kind: 'queued', pending })
  }

  async peek(): Promise<OxelotMutation | null> {
    const { chunks } = await this.loadState()
    const now = Date.now()
    for (const chunk of chunks) {
      const due = chunk.find((m) => m.nextRetryAt == null || m.nextRetryAt <= now)
      if (due) return due
    }
    return null
  }

  async flush(): Promise<{ delivered: number; deadLetters: number }> {
    if (this.flushing) return { delivered: 0, deadLetters: 0 }
    this.flushing = true
    try {
      if (this.lock) {
        // Blocking acquisition of the exclusive `oxelot-sync` lock: while a
        // drain runs in any realm (another tab, the service worker), exactly one
        // flusher is active. A concurrent flusher waits, then no-ops on the now
        // empty queue — this is what prevents double-delivering the shared
        // queue. (Chromium grants `ifAvailable` requests even under contention,
        // so skip-based arbitration is not reliable cross-realm; blocking is.)
        return await this.lock.withLock(SYNC_LOCK, () => this.drain())
      }
      return await this.drain()
    } finally {
      this.flushing = false
    }
  }

  async status(): Promise<{ pending: number; deadLetters: number }> {
    const dead = (await this.kv.get<OxelotMutation[]>(DEAD_KEY)) ?? []
    const head = await this.kv.get<unknown>(QUEUE_KEY)
    if (isManifest(head)) return { pending: head.count, deadLetters: dead.length }
    if (Array.isArray(head)) return { pending: head.length, deadLetters: dead.length }
    return { pending: 0, deadLetters: dead.length }
  }

  onStateChange(cb: (s: SyncState) => void): () => void {
    this.listeners.add(cb)
    return () => this.listeners.delete(cb)
  }

  /**
   * Load the live layout. Detects and migrates the legacy v1 single-array
   * layout: chunk keys are written BEFORE the manifest overwrites the legacy
   * array (the atomic switch point), so a crash mid-migration simply re-runs
   * it from the intact source array.
   */
  private async loadState(): Promise<{ manifest: QueueManifest; chunks: OxelotMutation[][] }> {
    const head = await this.kv.get<unknown>(QUEUE_KEY)
    if (isManifest(head)) {
      const chunks: OxelotMutation[][] = []
      for (let i = 0; i < head.chunkCount; i++) {
        const chunk = await this.kv.get<OxelotMutation[]>(chunkKey(head.base + i))
        chunks.push(Array.isArray(chunk) ? chunk : [])
      }
      return { manifest: head, chunks }
    }
    const legacy = Array.isArray(head) ? (head as OxelotMutation[]) : []
    const chunks = splitChunks(legacy, this.chunkSize)
    await this.writeLayout(chunks, 0, 0)
    return {
      manifest: {
        v: MANIFEST_VERSION,
        base: 0,
        count: legacy.length,
        chunkSize: this.chunkSize,
        chunkCount: chunks.length,
      },
      chunks,
    }
  }

  /**
   * Persist a whole new chunk layout in three phases: (1) survivor chunks go
   * to FRESH keys above the previous range so they are invisible until
   * (2) the manifest atomically switches the live view (single kv.set);
   * (3) stale keys from the previous range are tombstoned as `[]` (KvLike has
   * no delete). A crash before phase 2 leaves the old view fully intact —
   * stray fresh keys are simply overwritten by the next relayout. The base
   * advances only on progress (delivered > 0), so a permanently failing
   * server never grows the key space.
   */
  private async writeLayout(
    next: OxelotMutation[][],
    previousBase: number,
    previousChunkCount: number,
  ): Promise<void> {
    const base = previousBase + Math.max(previousChunkCount, 0)
    for (let j = 0; j < next.length; j++) await this.kv.set(chunkKey(base + j), next[j]!)
    const manifest: QueueManifest = {
      v: MANIFEST_VERSION,
      base,
      count: totalCount(next),
      chunkSize: this.chunkSize,
      chunkCount: next.length,
    }
    await this.kv.set(QUEUE_KEY, manifest)
    for (let i = 0; i < previousChunkCount; i++) await this.kv.set(chunkKey(previousBase + i), [])
  }

  /**
   * Checkpoint: persist only chunks touched since the last checkpoint, in the
   * CURRENT layout (in-place shrinkage), plus the manifest count. Order
   * matters — chunks first, manifest last — so a crash between them leaves a
   * stale advisory count that the next drain recomputes (self-healing).
   */
  private async persistDirty(
    chunks: OxelotMutation[][],
    dirty: Set<number>,
    manifest: QueueManifest,
  ): Promise<void> {
    for (const i of dirty) await this.kv.set(chunkKey(manifest.base + i), chunks[i]!)
    await this.kv.set(QUEUE_KEY, { ...manifest, count: totalCount(chunks) })
  }

  /**
   * Drain the queue, delivering only envelopes that are due (no pending backoff
   * period). An envelope is removed only after a successful delivery (pop-on-
   * success); dirty chunks are persisted every `checkpoint` processed
   * envelopes so a crash mid-drain cannot re-deliver more than `checkpoint`
   * already-sent envelopes. Transient failures increment `attempts`, stamp
   * `nextRetryAt`, and are kept for a later flush; permanent failures are
   * quarantined as dead letters. When anything was delivered, the surviving
   * envelopes are re-laid out into consecutive chunks (two-phase compaction).
   */
  private async drain(): Promise<{ delivered: number; deadLetters: number }> {
    const result = { delivered: 0, deadLetters: 0 }
    const { manifest, chunks } = await this.loadState()
    const dead = (await this.kv.get<OxelotMutation[]>(DEAD_KEY)) ?? []
    const total = totalCount(chunks)
    if (total === 0) {
      this.emit({ kind: 'idle' })
      return result
    }
    this.emit({ kind: 'syncing', pending: total })

    const now = Date.now()
    const dirty = new Set<number>()
    let attempted = 0
    for (let ci = 0; ci < chunks.length; ci++) {
      const chunk = chunks[ci]!
      let touched = false
      let ei = 0
      // Forward walk with in-place removal of the CURRENT index preserves
      // strict FIFO delivery order, and chunks[ci] stays accurate between
      // attempts so a checkpoint can fire after every single one.
      while (ei < chunk.length) {
        const m = chunk[ei]!
        if (m.nextRetryAt != null && m.nextRetryAt > now) {
          ei++
          continue
        }
        m.attempts += 1
        attempted++
        touched = true
        try {
          await this.deliver.deliver(m)
          chunk.splice(ei, 1)
          result.delivered++ // success → m is dropped (atomic pop)
        } catch (err) {
          m.lastError = err instanceof Error ? err.message : String(err)
          if (isDeadLetter(m.attempts)) {
            chunk.splice(ei, 1)
            dead.push(m)
            result.deadLetters++
          } else {
            m.nextRetryAt = now + nextRetryDelayMs(m.attempts)
            ei++
          }
        }
        if (attempted % this.checkpoint === 0) {
          dirty.add(ci)
          await this.persistDirty(chunks, dirty, manifest)
          dirty.clear()
          await this.kv.set(DEAD_KEY, dead)
        }
      }
      if (touched) dirty.add(ci)
    }
    if (result.delivered > 0 || result.deadLetters > 0) {
      // Progress: re-layout survivors into consecutive chunks starting above
      // the consumed range (two-phase compaction, see writeLayout).
      await this.writeLayout(splitChunks(chunks.flat(), this.chunkSize), manifest.base, manifest.chunkCount)
    } else if (dirty.size > 0) {
      // Nothing delivered/dead (pure backoff skips): fields changed in place.
      await this.persistDirty(chunks, dirty, manifest)
    }
    await this.kv.set(DEAD_KEY, dead)

    const pending = totalCount(chunks)
    this.emit(
      pending > 0
        ? { kind: 'queued', pending }
        : result.deadLetters > 0
          ? { kind: 'dead_letter', pending: 0, deadLetters: dead.length }
          : { kind: 'idle' },
    )
    return result
  }

  private emit(state: SyncState): void {
    for (const cb of this.listeners) cb(state)
  }
}

export interface FetchSyncDeliveryOptions {
  serverUrl: string
  fetchImpl?: typeof fetch
}

export class FetchSyncDelivery implements SyncDelivery {
  private readonly fetchImpl: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>

  constructor(private readonly options: FetchSyncDeliveryOptions) {
    // `fetch` is a method on the global scope (Window/WorkerGlobalScope) and
    // throws "Illegal invocation" when called through a stored reference. Bind
    // it so flush works from both the page and the service worker.
    this.fetchImpl = (options.fetchImpl ?? fetch).bind(globalThis)
  }

  async deliver(m: OxelotMutation): Promise<void> {
    let res: Response
    try {
      res = await this.fetchImpl(this.options.serverUrl, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: serializeMutation(m),
      })
    } catch (err) {
      const cause = err instanceof Error ? err.message : String(err)
      throw oxError('ERR_SYNC_NETWORK', `network failure during sync flush (${cause})`, err)
    }
    if (res.ok) return
    if (res.status >= 500 || res.status === 408 || res.status === 429) {
      throw oxError('ERR_SYNC_NETWORK', `retryable status ${res.status}`)
    }
    throw oxError('ERR_SYNC_REJECTED', `permanent status ${res.status}`)
  }
}

export const retryDelay = nextRetryDelayMs
export { deserializeMutation, SYNC_LOCK }
